### ISSUE TITLE
Type for function equal

### ISSUE THREAD

**Issue by mickeypearce** [deitry/testcomplete-ts-api#12]
Hey,
great project! I started with TestCompelte and I am already using it with vscode extension...

My project uses `equal` function a lot, is there a way to include a definition in your api?
https://support.smartbear.com/testcomplete/docs/reference/language/javascript/equal-method.html

**Comment by deitry** [comment]
Yep, it's possible, I will add this in the near future

**Comment by deitry** [comment]
Hi @mickeypearce ! Did you try latest version? Please tell if Is it working well for you

Also as a side question: do you set up it manually or use it via [VSCode extension](https://github.com/deitry/vscode-testcomplete)?

**Comment by mickeypearce** [comment]
@deitry Works, yes. Thanks. I use VSCode extension.
